language: php

php:
  - 7.2

env:
  global:
    - CC_TEST_REPORTER_ID=c58ccf176b673ee05954000d7e471dff14f74c85194a483152098503d3737ca1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer install
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
